name: Bump Cloudbeat version2

on:
  workflow_dispatch:
    inputs:
      cloudbeat_version:
        description: "The new cloudbeat version number to bump to"
        required: true
      integration_version:
        description: "The new integration version number to bump to"
        required: true

env:
  GITHUB_CI_TOKEN: ${{ secrets.FORK_TOKEN }}
  NEXT_CLOUDBEAT_VERSION: ${{ inputs.cloudbeat_version }}
  NEXT_INTEGRATION_VERSION: ${{ inputs.integration_version }}
  GH_TOKEN: ${{ github.token }}

jobs:
  cloudbeat:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Cloudbeat repo
        uses: actions/checkout@v4

      - name: exract version
        run: |
          version=$(grep defaultBeatVersion version/version.go | cut -f2 -d "\"")
          echo $version
          echo "CURRENT_CLOUDBEAT_VERSION=$version" >> $GITHUB_ENV
          echo "Bumping $version to $NEXT_CLOUDBEAT_VERSION"

      - name: Bump cloudbeat
        run: scripts/bump_cloudbeat.sh

  integration:
    needs: cloudbeat
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Integrations repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.FORK_TOKEN }}
          repository: orouz/integrations
          ref: main

      - name: Bump Integration
        run: |
          MANIFEST_PATH="packages/cloud_security_posture/manifest.yml"

          replace_manifest_version_vars() {
              MINOR_VERSION=$(echo $NEXT_CLOUDBEAT_VERSION | cut -d '.' -f1,2)
              echo "MINOR_VERSION is $MINOR_VERSION"

              PATCH_VERSION=$NEXT_CLOUDBEAT_VERSION
              echo "PATCH_VERSION is $PATCH_VERSION"

              # cis_gcp
              sed -i'' -E "s/cloudshell_git_branch=[0-9]+\.[0-9]+/cloudshell_git_branch=$MINOR_VERSION/g" $MANIFEST_PATH

              # cis_aws + vuln_mgmt_aws
              sed -i'' -E "s/cloudformation-cnvm-[0-9]+\.[0-9]+\.[0-9]+/cloudformation-cnvm-$PATCH_VERSION/g" $MANIFEST_PATH
              sed -i'' -E "s/cloudformation-cspm-ACCOUNT_TYPE-[0-9]+\.[0-9]+\.[0-9]+/cloudformation-cspm-ACCOUNT_TYPE-$PATCH_VERSION/g" $MANIFEST_PATH

              # cis_azure
              sed -i'' -E "s/cloudbeat%2F[0-9]+\.[0-9]+/cloudbeat%2F$PATCH_VERSION/g" $MANIFEST_PATH
          }

          create_integrations_pr() {
              local BRANCH="bump-to-$NEXT_CLOUDBEAT_VERSION"
              git config --global user.email "elasticmachine@users.noreply.github.com"
              git config --global user.name "Elastic Machine"
              git checkout -b "$BRANCH" main
              git add $MANIFEST_PATH
              git commit -m "Bump integration manifest to $NEXT_CLOUDBEAT_VERSION"
              git push origin $BRANCH
              gh auth login --with-token <<<"$GITHUB_CI_TOKEN"
              gh pr create --title "[Cloud Security] Update integration manifest" \
                      --body "Automated PR" \
                      --base "main" \
                      --head "$BRANCH"
          }

          replace_manifest_version_vars
          create_integrations_pr
