name: Update Integration

on:
  push:
    branches:
      - main
#   create:
#     branches:
#       # whenever a new release branch is created, this workflow will be triggered
#       - "[0-9].[0-9]+"

jobs:
  extract-version:
    outputs:
      stack_version: ${{ steps.extract_version.outputs.version }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Cloudbeat repo
        uses: actions/checkout@v4

      - name: Extract version from file
        id: extract_version
        run: |
          version=$(grep defaultBeatVersion version/version.go | cut -f2 -d "\"")
          echo "version=$version" >> $GITHUB_OUTPUT
          echo "Version is $version"

  modify-integration:
    needs: extract-version
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Integrations repo
        uses: actions/checkout@v4
        with:
          repository: orouz/integrations
          ref: main

      - name: Update URLs
        run: |
          new_version="${{ needs.extract-version.outputs.stack_version }}"
          echo "new_version is $new_version" 

          manifest_file_path="packages/cloud_security_posture/manifest.yml"
          cat $manifest_file_path



          sed -i '' -E "s/cloudshell_git_branch=[0-9]+\.[0-9]+/cloudshell_git_branch=$new_version/g" ./packages/cloud_security_posture/manifest.yml
