name: Update Integration

on:
  push:
    branches:
      - main
#   create:
#     branches:
#       # whenever a new release branch is created, this workflow will be triggered
#       - "[0-9].[0-9]+"

jobs:
  # extract-version:
  #   outputs:
  #     stack_version: ${{ steps.extract_version.outputs.version }}
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout Cloudbeat repo
  #       uses: actions/checkout@v4

  #     - name: Extract version from file
  #       id: extract_version
  #       run: |
  #         version=$(grep defaultBeatVersion version/version.go | cut -f2 -d "\"")
  #         echo "version=$version" >> $GITHUB_OUTPUT
  #         echo "Version is $version"

  modify-integration:
    # needs: extract-version
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Integrations repo
        uses: actions/checkout@v2
        with:
          repository: orouz/integrations
          ref: main

      # - name: Update URLs
      #   run: |
      #     echo 'check for repo files'
      #     ls

      #     manifest_file_path="packages/cloud_security_posture/manifest.yml"
      #     echo "manifest_file_path is $manifest_file_path"
      #     echo "here is manifst"
      #     cat $manifest_file_path

      #     echo "check for package?"
      #     ls packages/cloud_security_posture

      #     new_version="${{ needs.extract-version.outputs.stack_version }}"
      #     echo "new_version is $new_version"

      #     new_cloudshell_git_branch=$(echo $new_version | cut -d '.' -f1,2)
      #     echo "new_cloudshell_git_branch is $new_cloudshell_git_branch"

      #     new_cloud_formation_template=$new_version
      #     echo "new_cloud_formation_template is $new_cloud_formation_template"

      #     sed -i '' -E "s/cloudshell_git_branch=[0-9]+\.[0-9]+/cloudshell_git_branch=$new_cloudshell_git_branch/g" ./packages/cloud_security_posture/manifest.yml
      #     sed -i '' -E "s/cloud_formation_template=[0-9]+\.[0-9]+/cloud_formation_template=$new_cloud_formation_template/g" ./packages/cloud_security_posture/manifest.yml

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        id: cpr
        with:
          token: ${{ secrets.INTEGRATIONS_FORK_KEY }}
          commit-message: ${{ env.commit_message }}
          branch: ${{ env.branch_name }}
          title: ${{ env.commit_message }}
          body: ${{ env.commit_message }}
          base: ${{ env.branch }}
          committer: "Elastic Machine <elasticmachine@users.noreply.github.com>"
          author: "Elastic Machine <elasticmachine@users.noreply.github.com>"
      # - name: Create Pull Request
      #   run: |
      #     echo foo > foo.txt
      #     git add .
      #     git commit -m "Update foo"
      #     git config --global user.name 'Elastic Machine'
      #     git config --global user.email 'elasticmachine@users.noreply.github.com'
      #     gh pr create --base main --head "main" --title "[Cloud Security] Update manifest" --body "Your pull request description here" --author "Elastic Machine <elasticmachine@users.noreply.github.com>"
