name: Update Integration

on:
  push:
    branches:
      - main
#   create:
#     branches:
#       # whenever a new release branch is created, this workflow will be triggered
#       - "[0-9].[0-9]+"

jobs:
  extract-version:
    outputs:
      stack_version: ${{ steps.extract_version.outputs.version }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Cloudbeat repo
        uses: actions/checkout@v4

      - name: Extract version from file
        id: extract_version
        run: |
          version=$(grep defaultBeatVersion version/version.go | cut -f2 -d "\"")
          echo "version=$version" >> $GITHUB_OUTPUT
          echo "Version is $version"

  modify-integration:
    needs: extract-version
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Integrations repo
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.FORK_TOKEN }}
          repository: orouz/integrations
          ref: main

      - name: Update URLs
        run: |
          manifest_file_path="packages/cloud_security_posture/manifest.yml"
          echo "manifest_file_path is $manifest_file_path"

          new_version="${{ needs.extract-version.outputs.stack_version }}"
          echo "new_version is $new_version"

          CLOUDBEAT_BRANCH=$(echo $new_version | cut -d '.' -f1,2)
          echo "CLOUDBEAT_BRANCH is $CLOUDBEAT_BRANCH"

          TEMPLATE_VERSION=$new_version
          echo "TEMPLATE_VERSION is $TEMPLATE_VERSION"

          sed -i -E "s/cloudshell_git_branch=[0-9]+\.[0-9]+/cloudshell_git_branch=$CLOUDBEAT_BRANCH/g" $manifest_file_path
          sed -i -E "s/cloudformation-cnvm-[0-9]+\.[0-9]+\.[0-9]+/cloudformation-cnvm-$TEMPLATE_VERSION/g" $manifest_file_path
          sed -i -E "s/cloudformation-cspm-ACCOUNT_TYPE-[0-9]+\.[0-9]+\.[0-9]+/cloudformation-cspm-ACCOUNT_TYPE-$TEMPLATE_VERSION/g" $manifest_file_path

          # sed -i -E "s/(cloudformation-cnvm-)[0-9]+\.[0-9]+\.[0-9]+/\1$TEMPLATE_VERSION/g" $manifest_file_path
          # sed -i -E "s/(cloudformation-cspm-ACCOUNT_TYPE-)[0-9]+\.[0-9]+\.[0-9]+/\1$TEMPLATE_VERSION/g" $manifest_file_path

          # cloudbeat%2Fmain
          git diff

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        id: cpr
        with:
          token: ${{ secrets.FORK_TOKEN }}
          commit-message: "Update manifest template versions"
          branch: "update-cloudbeat-integration"
          title: "[Cloud Security] Update manifest template versions"
          body: "Automated PR"
          base: ${{ env.branch }}
          committer: "Elastic Machine <elasticmachine@users.noreply.github.com>"
          author: "Elastic Machine <elasticmachine@users.noreply.github.com>"
